"""Add foreign key constraints

Revision ID: 58ebd3922c0e
Revises: bd083dbad729
Create Date: 2026-02-12 15:22:55.404613
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58ebd3922c0e'
down_revision: Union[str, None] = 'bd083dbad729'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'commitments', 'deals', ['deal_id'], ['id'])
    op.create_foreign_key(None, 'commitments', 'contacts', ['contact_id'], ['id'])
    op.create_foreign_key(None, 'contacts', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'deals', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'deals', 'contacts', ['contact_id'], ['id'])
    op.create_foreign_key(None, 'interactions', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'interactions', 'contacts', ['contact_id'], ['id'])
    op.create_foreign_key(None, 'notes', 'deals', ['deal_id'], ['id'])
    op.create_foreign_key(None, 'notes', 'contacts', ['contact_id'], ['id'])
    op.create_foreign_key(None, 'privacy_consents', 'contacts', ['contact_id'], ['id'])
    op.create_foreign_key(None, 'relationships', 'contacts', ['contact_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'deals', ['deal_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'contacts', ['contact_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'relationships', type_='foreignkey')
    op.drop_constraint(None, 'privacy_consents', type_='foreignkey')
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_constraint(None, 'interactions', type_='foreignkey')
    op.drop_constraint(None, 'interactions', type_='foreignkey')
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_constraint(None, 'commitments', type_='foreignkey')
    op.drop_constraint(None, 'commitments', type_='foreignkey')
    # ### end Alembic commands ###
