@echo off
title Launching Costanza...
echo Starting Costanza backend...
powershell -ExecutionPolicy Bypass -File "C:\Users\ManiPadisetti\Dropbox\Desktop DB\Books and Articles Mani\Books\Almost Magic Tech Lab AMTL\Source and Brand\services.ps1" start costanza
echo Starting Costanza desktop...
start "" "C:\Users\ManiPadisetti\Dropbox\Desktop DB\Books and Articles Mani\Books\Almost Magic Tech Lab AMTL\Source and Brand\CK\desktop-apps\dist\costanza\win-unpacked\Costanza.exe"
exit
