@echo off
title Launching Junk Drawer...
echo Starting Junk Drawer backend...
powershell -ExecutionPolicy Bypass -File "C:\Users\ManiPadisetti\Dropbox\Desktop DB\Books and Articles Mani\Books\Almost Magic Tech Lab AMTL\Source and Brand\services.ps1" start junkdrawer
echo Starting Junk Drawer desktop...
start "" "C:\Users\ManiPadisetti\Dropbox\Desktop DB\Books and Articles Mani\Books\Almost Magic Tech Lab AMTL\Source and Brand\CK\desktop-apps\dist\junk-drawer\win-unpacked\Junk Drawer.exe"
exit
