@echo off
title Launching Ripple CRM...
echo Starting Ripple CRM backend...
powershell -ExecutionPolicy Bypass -File "C:\Users\ManiPadisetti\Dropbox\Desktop DB\Books and Articles Mani\Books\Almost Magic Tech Lab AMTL\Source and Brand\services.ps1" start ripple
echo Starting Ripple CRM desktop...
start "" "C:\Users\ManiPadisetti\Dropbox\Desktop DB\Books and Articles Mani\Books\Almost Magic Tech Lab AMTL\Source and Brand\CK\desktop-apps\dist\ripple\win-unpacked\Ripple CRM.exe"
exit
