@echo off
title Launching Touchstone...
echo Starting Touchstone backend...
powershell -ExecutionPolicy Bypass -File "C:\Users\ManiPadisetti\Dropbox\Desktop DB\Books and Articles Mani\Books\Almost Magic Tech Lab AMTL\Source and Brand\services.ps1" start touchstone
echo Starting Touchstone desktop...
start "" "C:\Users\ManiPadisetti\Dropbox\Desktop DB\Books and Articles Mani\Books\Almost Magic Tech Lab AMTL\Source and Brand\CK\desktop-apps\dist\touchstone\win-unpacked\Touchstone.exe"
exit
