@echo off
title Launching The Workshop...
echo Starting The Workshop backend...
powershell -ExecutionPolicy Bypass -File "C:\Users\ManiPadisetti\Dropbox\Desktop DB\Books and Articles Mani\Books\Almost Magic Tech Lab AMTL\Source and Brand\services.ps1" start workshop
echo Starting The Workshop desktop...
start "" "C:\Users\ManiPadisetti\Dropbox\Desktop DB\Books and Articles Mani\Books\Almost Magic Tech Lab AMTL\Source and Brand\CK\desktop-apps\dist\workshop\win-unpacked\The Workshop.exe"
exit
